apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ include "todolist.fullname" . }}-ingress
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todolist.name" . }}
  ingress:
    - fromEntities:
        - ingress
      toPorts:
        - ports:
            - port: "5000"
              protocol: TCP
