#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="${ENV_FILE:-.local/release-please.env}"
RUNNER_HOME="${RUNNER_HOME:-$HOME/Library/Application Support/todolist-actions-runner}"
LAUNCH_AGENT="$HOME/Library/LaunchAgents/com.todolist.local-kind-runner.plist"

banner "TodoList automation setup"

stage "Validate prerequisites"
say "This runner executes deployments only after merges in main."
for command in docker kind kubectl helm terraform git gh curl tar make jq; do
  if ! command -v "$command" >/dev/null 2>&1; then
    warn "missing required command: $command"
    exit 1
  fi
done
if ! docker info >/dev/null 2>&1; then
  warn "Docker Desktop is not available. Start it and run this wizard again."
  exit 1
fi
if ! gh auth status >/dev/null 2>&1; then
  warn "GitHub CLI is not authenticated. Run gh auth login and retry."
  exit 1
fi
REPOSITORY=$(gh repo view --json nameWithOwner --jq .nameWithOwner)
if [[ "$REPOSITORY" != "mcarval4/todolist-app" ]]; then
  warn "Run this wizard from the mcarval4/todolist-app checkout."
  exit 1
fi
say "Prerequisites are ready."
pause

stage "Create release-please token"
say "Create a fine-grained PAT for the todolist-app repository only."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Set an expiration and select resource owner mcarval4 and repository todolist-app."
step "Grant Contents, Pull requests and Issues read/write permissions."
step "Generate the token, copy it now, then paste it below."
ask_secret RELEASE_PLEASE_TOKEN "Paste the fine-grained PAT:"
if [[ -z "$RELEASE_PLEASE_TOKEN" ]]; then
  warn "A token is required to create release PRs."
  exit 1
fi
mkdir -p "$(dirname "$ENV_FILE")"
write_env RELEASE_PLEASE_TOKEN "$RELEASE_PLEASE_TOKEN"
chmod 600 "$ENV_FILE"
if printf '%s' "$RELEASE_PLEASE_TOKEN" | gh secret set RELEASE_PLEASE_TOKEN --repo "$REPOSITORY" >/dev/null 2>&1; then
  WRITTEN_SECRET+=("RELEASE_PLEASE_TOKEN")
  say "GitHub secret RELEASE_PLEASE_TOKEN configured for $REPOSITORY."
else
  warn "Could not configure RELEASE_PLEASE_TOKEN. Set it manually before merging this feature."
  exit 1
fi
pause

stage "Register local runner"
RUNNER_NAME="$(scutil --get ComputerName | tr ' ' '-' | tr '[:upper:]' '[:lower:]')-local-kind"
say "The runner will be registered only for $REPOSITORY with labels macos and local-kind."
if ! confirm "Download and register the runner now?"; then
  warn "Runner registration skipped. Re-run this wizard when ready."
  finish
  exit 0
fi
mkdir -p "$RUNNER_HOME"
needs_registration=true
if [[ -f "$RUNNER_HOME/.runner" ]]; then
  RUNNER_LABELS=$(gh api "repos/$REPOSITORY/actions/runners" | jq -r --arg name "$RUNNER_NAME" '[.runners[] | select(.name == $name) | .labels[].name] | join(" ")')
  if [[ " $RUNNER_LABELS " == *" macos "* && " $RUNNER_LABELS " == *" local-kind "* ]]; then
    say "Runner already registered with required labels."
    needs_registration=false
  else
    warn "Existing runner registration is missing required labels and will be replaced."
    launchctl bootout "gui/$(id -u)" "$LAUNCH_AGENT" >/dev/null 2>&1 || true
    REMOVAL_TOKEN=$(gh api --method POST "repos/$REPOSITORY/actions/runners/remove-token" --jq .token)
    "$RUNNER_HOME/config.sh" remove --unattended --token "$REMOVAL_TOKEN"
  fi
fi
if [[ "$needs_registration" == true ]]; then
  if [[ ! -f "$RUNNER_HOME/config.sh" ]]; then
  RUNNER_URL=$(gh api repos/actions/runner/releases/latest --jq '.assets[] | select(.name | test("^actions-runner-osx-arm64-[0-9].*\\.tar\\.gz$")) | .browser_download_url')
  if [[ -z "$RUNNER_URL" ]]; then
    warn "Could not locate the ARM64 macOS runner download."
    exit 1
  fi
  curl --fail --location "$RUNNER_URL" --output "$RUNNER_HOME/runner.tar.gz"
  tar -xzf "$RUNNER_HOME/runner.tar.gz" -C "$RUNNER_HOME"
  rm "$RUNNER_HOME/runner.tar.gz"
  fi
  REGISTRATION_TOKEN=$(gh api --method POST "repos/$REPOSITORY/actions/runners/registration-token" --jq .token)
  "$RUNNER_HOME/config.sh" --unattended --url "https://github.com/$REPOSITORY" --token "$REGISTRATION_TOKEN" --name "$RUNNER_NAME" --labels "macos,local-kind" --work _work
fi
write_env RUNNER_HOME "$RUNNER_HOME"
write_env RUNNER_NAME "$RUNNER_NAME"
pause

stage "Install persistent LaunchAgent"
say "LaunchAgent starts the runner after this user logs in. Docker Desktop must also start after login."
if ! confirm "Install and load the LaunchAgent now?"; then
  warn "Runner is registered but will not start automatically."
  finish
  exit 0
fi
mkdir -p "$HOME/Library/LaunchAgents"
cat > "$LAUNCH_AGENT" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.todolist.local-kind-runner</string>
  <key>ProgramArguments</key><array><string>$RUNNER_HOME/run.sh</string></array>
  <key>WorkingDirectory</key><string>$RUNNER_HOME</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$RUNNER_HOME/runner.log</string>
  <key>StandardErrorPath</key><string>$RUNNER_HOME/runner-error.log</string>
</dict></plist>
PLIST
launchctl bootout "gui/$(id -u)" "$LAUNCH_AGENT" >/dev/null 2>&1 || true
launchctl bootstrap "gui/$(id -u)" "$LAUNCH_AGENT"
launchctl print "gui/$(id -u)/com.todolist.local-kind-runner" >/dev/null
say "Runner service is active."
finish
